---
# tasks file for webserver
- name: install httpd package
  package:
      name: "httpd"
      state: present
  register: x

- name: document root dir
  file:
      state: directory
      dest:  "{{ dcdir }}"
  register: y
  tags: webgit

- name: conf web server
  template:
     dest: /etc/httpd/conf.d/satvi.conf
     src: templates/localconf.conf.j2
  tags: webconf
  notify: service httpd


- name: copy web page from url
  get_url:
      dest: "{{ dcdir }}"
      url: "https://raw.githubusercontent.com/satvikakolisetty/ansible-aws/master/index.html"
  when: y.failed ==  false
  tags: webgit

- name: start service for web
  service:
      name: "httpd"
      state: started


